#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
jira_branch=$(echo $branch | egrep -o '[A-Z]{3,}-\d+')
jira_msg=$(egrep -o '[A-Z]{3,}-\d+' "$1")


if [[ "$jira_msg" != "" ]]; then
	if [[ "$jira_msg" != "$jira_branch" ]]; then
		echo "WARNING: JIRA codes in branch name and commit message didn't match"
	fi
else
	if [[ "$jira_branch" != "" ]]; then
		sed -i '' '1s/^/'$jira_branch' /' $1
	else
		echo >&2 "\t\t🚨\t🚨\t🚨\t🚨\t🚨\t🚨\t🚨"
		echo >&2
		echo >&2 "\t\t🚨\tCommit message requires JIRA code.\t🚨"
		echo >&2
		echo >&2 "\t\t🚨\t🚨\t🚨\t🚨\t🚨\t🚨\t🚨"
		exit 1
	fi
fi

